---
- name: create yum repo
  get_url: >
            url=http://packages.erlang-solutions.com/rpm/centos/erlang_solutions.repo
            dest=/etc/yum.repos.d/
- name: install dependency packages
  yum: name={{ item }} state=present
  with_items:
    - epel-release
    - gcc-c++
    - git
    - make
    - ncurses-devel
    - openssl-devel
    - esl-erlang
- name: verify elixir installation
  command: iex --version
  sudo: no
  register: which_iex
  ignore_errors: true
- name: compilation (clone)
  git: >
        repo=https://github.com/elixir-lang/elixir.git
        dest={{ elixir_lang.dest.root }} update=no
        version={{ elixir_lang.version }}
- name: compilation (build started)
  command: make clean install chdir={{ elixir_lang.dest.root }}
  when: which_iex | failed